language: node_js
node_js:
  - lts/*
install:
  - npm install
  - mkdir docs/.vuepress/dist/unsplash -p
  - cp unsplash/images.json docs/.vuepress/dist/unsplash/images.json
script:
  - npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: sanjabteam/sanjabteam.github.io
  target_branch: master
  on:
    branch: master
